### ISSUE TITLE
Ubuntu 22.04.02 LTS N64 not Shown in v126 from Ubuntu Repo, Compiling from Source v131 Missing udev Input Driver

### ISSUE THREAD

**Issue by mikeburns** [higan-emu/ares#1001]
I installed ares on Ubuntu 22.04.02 LTS using `apt-get` and it installed v126 from the Ubuntu repo.  This works fine, but there is no N64, even though there are N64 video settings.  So I compiled v131 from source and got N64 plus a whole bunch of other emulators, which is cool, but there is no `udev` input driver, so my USB N64 controller I use is not detected.  It just has `Xlib`.

Is there a flag I can set to install `udev` drivers in v131, or is there a known bug in v126/the Ubuntu repo version that doesn't load N64 that I can fix?  Or maybe someone can tell me how to get a generic USB controller to work with `Xlib` input drivers?

**Screenshots**
v126: no N64 available
![image](https://user-images.githubusercontent.com/30668/222132048-b89debd3-53d1-4c7c-a3e3-5af3510f6ed9.png)

v131: no `udev` input drivers available
![image](https://user-images.githubusercontent.com/30668/222132905-136c9d8a-ce0c-4e96-b1dc-745c245ed317.png)

**Comment by Screwtapello** [comment]
Hm. The ares README [suggests](https://github.com/ares-emulator/ares/blob/master/README.md#nix-building) that it needs the following packages installed:

* `g++` 
* `make`
* `pkg-config`
* `libgtk-3-dev`
* `libcanberra-gtk-module`
* `libgl-dev`
* `libasound2-dev`

...but [the CI build script](https://github.com/ares-emulator/ares/blob/68226281353f9f2fc1cf7e04164d3daa1e3aa99b/.github/workflows/build.yml#L65) lists:

* `libsdl2-dev`
* `libgtk2.0-dev`
* `libao-dev`
* `libopenal-dev`

On top of that, I would have expected something like `libudev-dev` for udev input support; that might be implied by the SDL2 dev support?

How many of those packages do you have installed on the system where you built ares?

**Comment by LukeUsher** [comment]
Regarding missing N64:

Debian (and Ubuntu) took the decision to disable N64 emulation, as it uses SSE4.X which they determined is too high of a requirement, this specific aspect is outside of our control.

This also means they compile with a lower level of optimisations than we would recommend, making their releases perform worse than official/self compiled builds.

**Comment by mikeburns** [comment]
@Screwtapello I had everything except for `libao-dev` and `libopenal-dev`.  I DID have `libudev-dev` installed.  I installed the missing libraries and recompiled, but still no `udev` input drivers.

@LukeUsher thanks for the info!  I'll keep trying to get the self-compiled version working with my controller.  I've been using Linux for 20 years but only via CLI as web servers, so this is my first foray into using Linux GUI as my main OS.  Will either try to figure out why `udev` is not loading or figure out how to get `xlib` to recognize my USB controller.

**Comment by remutro** [comment]
@mikeburns @Screwtapello @LukeUsher 

I'm running Ubuntu 22.04.2 LTS on my secondary system and originally had the same problem as described here. a couple of things:

- I'm not sure why the libao-dev or libopenal-dev libraries are required or part of CI build. I don't believe they are needed as I've never installed them on my system in order to build ares. I doubled check again and those packages are absent from install and I used a vanilla Ubuntu/Gnome installation. I also suspect that the libgtk2.0-dev package may be installed as a dependency for other packages that would normally be present on installs with a desktop environment installed, where I'm assuming on the CI builds the system is terminal based and doesn't have a desktop environment installed. 
- More importantly for this issue, I originally also only had xlib available and it didn't work with my controller. I would focus on using SDL for input as it has greater compatibility. Make sure you install the following packages and clean/rebuild ares so that it is picked up:

`libsdl2-2.0-0 libsdl2-dev`

After installation and rebuilding ares, then you should be able to set SDL as your main input driver. There are a number of additional dependencies installed with the SDL packages, which also includes what is needed for udev to become available as well, but I still recommend sticking with SDL. A reminder that by default the Linux build doesn't copy the Shaders and Database directory into the output directory where the ares executable is built. Either copy them manually or run "make install" after building to install everything into the defined install directory (there is more information about this in the main README file).

I'll work on updating the README file with this information. I've been meaning to update the README to clean up some sections and also add information about compiling with clang anyways.

**Comment by LukeUsher** [comment]
Libao and libopenal are not *required* to build ares, but they are required to build those audio drivers, if you want all the available options compiled in.

**Comment by remutro** [comment]
Ah...OK. I've always used the ALSA drivers and they work without issue. I'll make sure this is specified in the README update as well.

**Comment by LukeUsher** [comment]
Not a bug; just ares adapting to match the build environment it was compiledi n.
