### ISSUE TITLE
[NES] digital devil story - megami tensei 1 english patch

### ISSUE THREAD

**Issue by powerpuffboysz** [higan-emu/ares#1047]
The regular japanese rom of Digital Devil Monogatari: Megami Tensei works just fine however this patch: https://www.romhacking.net/translations/2287/

It "hangs" for lack of a better term on a black screen when loading a patched rom but the fps counter changing suggests something is still technically loading behind the black screen. I can confirm this patch works fine in other nes emulators like fceux

**Comment by asiekierka** [comment]
Can you confirm it works on real hardware - or, at the very least, a highly accurate emulator like Mesen?

**Comment by powerpuffboysz** [comment]
I unfortunately cannot test real hardware however mesen seems to work fine

**Comment by HeroponRikiBestest** [comment]
Real hardware footage: https://www.youtube.com/watch?v=VoeRer3GI-k

**Comment by FitzRoyX** [comment]
This patch expands the prg rom from 128 to 256kb, and every board on nescartdb that uses the namco 108/118 chip has a prg that is 128kb. So I'm guessing ares is expecting that as the maximum possible size?

**Comment by LukeUsher** [comment]
According to NESDEV Wiki (https://www.nesdev.org/wiki/INES_Mapper_206) the Namco 118/108 board does not support more than 128kb of prg rom; so this rom hack would not work if used on a real Namco cartridge; only on a flash cart that emulates a version of the chip that doesn't really exist..

Not really sure what to do here; we *could* fix it, but then we're not emulating a real Namco 118/108 anymore; 

It most likely works on other emulators and flash carts because they emulate the MMC3 instead of the Namco board; MMC3 is mostly compatible but supports 256KB

The correct solution here would likely to be for the rom header to be updated by the patch author to use MMC3; and fix anything in the rom that may break as a result.

**Comment by LukeUsher** [comment]
Our very own @invertego has created an updated patch that ports the game to use MMC3 rather than Namco1X8 mapper; I would suggest using this patch if you wish to play the romhack in ares, as MMC3 does support larger roms and doe snot require any hacks/inaccurate behaviours to be implemented.

 https://www.romhacking.net/translations/6907/
