### ISSUE TITLE
[MD] DEcapAttack: Left-Right input isn't working

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#1177]
**Describe the issue**
Strangely enough, in this game the buttons left and right doesn't work properly. This happens in both 3-button pad and fighting pad.
Any other Mega Drive tested with the same configuration works normally.

**Rom Information**
```
Name: DEcapAttack (USA, Europe, Korea) (En).md
Size: 524288 bytes (512 KiB)
SHA256: c098e27151e4494783e07e7007c59113c9d2616d13c80e74135df5c9781e611e
```

**Comment by invertego** [comment]
@TascoDLX 

This is caused by some sloppy code in Decap Attack that works by luck on real hardware.  This was not a problem in ares until b984bb52e90d8bb1cf5a2b84320bb51b3048fa0e, which generally made ares' controller port emulation more accurate but doesn't model the timing of actual hardware.

A fuller description of the correct behavior is given here:
https://github.com/ekeeke/Genesis-Plus-GX/issues/63#issuecomment-172347221

The author of picodrive opted to simply not emulate the pull-up effect on the select pin, which I agree seems pretty useless:
https://github.com/notaz/picodrive/commit/1d366b1ad9362fd463c42979c8a687dfc7f46c46

**Comment by invertego** [comment]
My diagnosis from before was a little off; while it's true these games are sensitive to pull-up on the TH pin, ares doesn't emulate that yet. Some other fixes where enough to make this game happy.
