### ISSUE TITLE
[PS1] Dualshock controller is missing "analog" button

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#1245]
Various PS1 games need the analog button to activate the "analog mode" for use in the compatible games.

**Comment by PeterSamuels** [comment]
Works as designed.
From Luke usher:
"Yes and no. The real controller defaults to digital mode with the analog button to toggle. Ares defaults to analog mode and doesn’t expose the analog button right now because I didn’t want to require the use of a hotkey to swap and modern game pads don’t have enough mappable buttons to put it on the controller
The ps/Xbox meta button would be useful but it can’t be used because windows will launch Xbox game bar or steam will open if you press it
I figured having the gui to swap between digital and analog controllers and just making the analog controller analog by default for now is the best middle ground for usability. Otherwise you’d select the analog controller and wonder why it wouldn’t work as analog"
