### ISSUE TITLE
[Nintendo 64] World Driver Championship

### ISSUE THREAD

**Issue by murilosouzaengenharia** [higan-emu/ares#1265]
Game just work in audio. Video shows black screen (and a white block on the game title screen) in ares v133. After that, I can't see the options to make it through into the gameplay. I don't know if there's some customization to make it work properly. That happens for the two region versions (USA and Europe).

World Driver Championship (USA).zip
SHA256:
355f08802b4b9263bbbfb6a874c330182db43c8fc287ca8b3fc9b67ffceca937

World Driver Championship (Europe) (En, Fr, De, Es, It).zip
SHA256:
d5181d249754264b5c53f1ef2ec4b96d81256c1495a5efbbbb044440deb76136

```

**Comment by kev4cards** [comment]
I was neither able to reproduce in v133 nor a current nightly with the USA region of the game. What are your device specifications (OS, CPU, GPU, GPU driver version, etc.)? Additionally, could you provide the SHA256 for the unzipped, dumped ROMs? I can't tell if your dumped ROM is correct based off of the zip.

**Comment by murilosouzaengenharia** [comment]
Just in case, I've downloaded the older ares versions since v127 until v132.

Screen is ok, despite accuracy and fps, for all those older versions.
Detected better fps from v131, around 35 fps on title screen (felt like half speed).

It seems the black or buggy screen also occurs to "easier" emulated games in the current v133.

About specs:
Notebook Lenovo
Windows 10 Home Single Language (22H2)
Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz   2.60 GHz
4,00 GB (3,90 GB)
DirectX 12
My notebook hasn't any dedicated GPU.

About SHA256 hashes from 7-zip:
World Driver Championship (USA).z64
e8e3734c5d2453c3a4bc940862545e2b84bdd65299e432548276fd71bccdfd97

World Driver Championship (Europe) (En,Fr,De,Es,It).z64
535c6b9430f74e36e1347f20e656eeb662af699c40a868e1d4a6bdd3c577f7d4

**Comment by kev4cards** [comment]
I apologize for responding back so late. Your dumps for World Driver Championship are good. So, the issue lies outside the ROM. In this case, you had success playing in v132 because your computer was automatically falling back to the MAME renderer due to insufficient Vulkan support for paraLLEl-RDP (requires Vulkan 1.1 whereas your CPU's integrated graphics has Vulkan 1.0). The MAME renderer has since been removed by the release of v133. This was because cross-platform support had recently been met for paraLLEl-RDP, and the MAME renderer was not really a performant solution as most users even with newer processors struggled to reach full emulation speed. Therefore, your computer is not capable of running the N64 core within ares at full emulation speed. You can revert the commit to remove the MAME renderer if you wish and compile on top of the latest commit. I do not think the low performance would be worth it, though, for a casual play-through.

**Comment by murilosouzaengenharia** [comment]
Thank you for explaining the details! I completely understand what happened in my case. At the same time I'm kinda sad for my low-end pc can't run well N64 games on ares (for now), I'm excited to see this emulator becoming more accurate and optimized in so many platforms. Of course there's a long road to perfection. But it's promissing how a relative new emulator is getting so far for gaming preservation. There're plenty of emulators that can run focusing in speed but lacking accuracy. That's the importance of this emulator. I hope it's a matter of time ares has to become the reference for a free and open source multiplatform emulator, easy to run, accurate and optimized as possible. Keep the great work! You guys have my respect!

**Comment by kev4cards** [comment]
Certainly. I'm glad you like the emulator.

I believe your computer will not be able to run N64 games even with an efficient non-Vulkan renderer given how ares chooses to run the N64 with accurate timings and clock behavior in mind. A high-end 6th or 7th generation Intel CPU or AMD equivalent in terms of single-core performance with a dedicated GPU should be adequate for most of the games. So, at minimum, you will want that if you are in the market for a new PC. A high-end 10th or 11th generation Intel CPU with a dedicated GPU should allow for full speed in all N64 games. Of course, this is with how the N64 is currently being emulated. The performance demand could increase or decrease depending upon later changes.

Since this has issue has been determined to not be an emulation issue, may you please close it? Thanks in advance.

**Comment by murilosouzaengenharia** [comment]
Thanks! And sry for didn't close. I didn't know the closing issue was up to me hehe
