### ISSUE TITLE
[Feature Request] Have ares look for .rom when loading game in MSX and MSX2 cores

### ISSUE THREAD

**Issue by PeterSamuels** [higan-emu/ares#1282]
**Is your feature request related to a problem? Please describe.**
.rom is the standard extension for MSX and MSX2 cartridge ROMs (see for example, No-Intro's database). This is to differentiate it from .dsk for floppy disk games (which ares doesn't support). ares right now looks for .msx and .msx2 only. Since ares looks for .bin for Atari and Mega Drive, I think it would make sense.

**Describe the solution you'd like**
Have ares look for .rom. Doesn't need to support drag and drop.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by FitzRoyX** [comment]
Using generic extensions for non-generic data is bad practice and will never be standard no matter how many years people did it. It's like asking someone to hand you a piece of metal instead of a fork and expecting them to understand what you mean. No-intro sets (the ones people should be using) haven't been .rom for 10+ years and it's not even that hard to rename files with a batch rename utility.

**Comment by PeterSamuels** [comment]
> Using generic extensions for non-generic data is bad practice and will never be standard no matter how many years people did it. It's like asking someone to hand you a piece of metal instead of a fork and expecting them to understand what you mean. No-intro sets (the ones people should be using) haven't been .rom for 10+ years and it's not even that hard to rename files with a batch rename utility.

I was looking at the dat-o-matic on the website, not a romset. Maybe I misunderstand how No-intro works. Sorry.

**Comment by FitzRoyX** [comment]
No you're right, they are .rom currently. Either I was thinking of md/bin or they recently changed them back to .rom. I'll have to find out but it doesn't really change my opinion on it being bad. We will never transition to better extensions if emulators keep supporting the old ones.

**Comment by Kawa-oneechan** [comment]
With Atari and Genedrive ROMs, using `.bin` is stupid because *all* files are binary, even when they're plain text. They should be `.smd` or `.gen` for the latter (but not `.md` if you ask me because Markdown), something like `.a26` for the former, depending on *which* Atari we're talking.

With MSX/MSX2 ROMs, `.rom` is perhaps only a little less stupid since *all but one* cartridge-based systems use ROMs, and then it becomes just as stupid again when you can't tell MSX ROMs from MSX2 ones because they *both* use `.rom`.

If it were my call, Ares wouldn't support `.bin` for Atari and Megasis either. Thankfully, it isn't.

**Comment by LukeUsher** [comment]
Honestly I'm happy with adding support for more extensions as a convenience, so long as said new extensions are the same binary format and don't require additional code to support.

This rules out .smd for megadrive, since that is an interleaved format designed for the Super Magic Drive copier, but there's no reason we cannot support .bin or .rom where it is considered the standard format, so long as you are happy with autodetect not working for those games.

**Comment by LukeUsher** [comment]
Added in da9c82956ab0a2dc8f4019f9e9bdc01336d18e57
