### ISSUE TITLE
[SNES] Top Racer Crossroads

### ISSUE THREAD

**Issue by paulomanrique** [higan-emu/ares#1420]
**Describe the issue**
Menus work fine, when starting the race, we can hear the music in the background but no image appears and never progresses.

**Rom Information**

This is an "official hack", of the first Top Racer, on the new "Top Racer Collection". The rom can be found in the [demo version of the game on steam](https://store.steampowered.com/app/2214000/Top_Racer_Collection/), in the folder: `C:\Program Files (x86)\Steam\steamapps\common\Top Racer Collection Demo\TopRacerCollectionDemo_Data\StreamingAssets`

```
file: TRC.smc
sha256: 00921f9fb3823e3735f3259a7c1fba47fec4948b6799c9ef1bc9996ce5174c5b

game
  name:     TRC
  title:    TRC
  label:    TOP RACER CROSSROADS
  region:   NTSC
  revision: 1.0
  board:    LOROM
    memory
      type: ROM
      size: 0x80000
      content: Program

```

**Comment by remutro** [comment]
One question: does this "official hack" run on real hardware? If it doesn't, then it will never run on ares either.

**Comment by vaguerant** [comment]
Seems unlikely that it would run on real hardware. I had a look at it and there's just odd chunks of code zeroed out. I'm guessing it's deliberate obfuscation to discourage piracy; their emulator probably fills in the missing data at runtime.

To the original filer, there is an earlier release of this hack floating around online under the name *Top Gear Crossroads Horizon Chase*.

While the version you've got is based on `Top Racer (Japan) (En).sfc` (No-Intro naming), the existing version is based on `Top Gear (USA).sfc` and includes none of the presumed anti-piracy functionality. The contents appear to be the same: in-game graphics for four new cars replace the original vehicles, but the menu graphics are unchanged, because *Top Racer Collection* has its own menu system which bypasses the in-game menus.

**Comment by paulomanrique** [comment]
That makes a lot of sense. I will close this topic, thanks all :)
