### ISSUE TITLE
32x - knuckles chaotix - slowdown & bad audio (repeated cracking sound)

### ISSUE THREAD

**Issue by goodstuff626** [higan-emu/ares#1424]
Before submitting an issue, please use the search to make sure an issue doesn't already exist, you should also make sure your rom is not a bad dump, by comparing against the hashes in the No-Intro (Cartridges) or Redump (CD-ROM) databases.

**Describe the issue**

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred);.
The easiest way to do this is to open the game in ares, and go to "Tools -> Manifest" and copy/paste the contents.

```
file: Some Game (REGION).ext
sha256: <hash>
```
game
  sha256: 70e1a92a982f2684be3bc315267e545fb9c530d533fd62b6d38bb625541ed957
  name:   Knuckles' Chaotix (Japan, USA) (En)
  title:  Knuckles' Chaotix (Japan, USA) (En)
  label:  CHAOTIX
  label:  CHAOTIX
  serial: GM MK-84503-00
  region: NTSC-J, NTSC-U
  board
    memory
      type: ROM
      size: 0x300000
      content: Program
    memory
      type: RAM
      address: 0x200000
      size: 0x200
      content: Save
      mode: lower

Using opengl synchronize with wasapi and games audio sounds bad with repeated cracking sound, and gameplay slows down randomly. I switched to different audio output modes and none fixed the issues. I played same rom with kega fusion emulator and it played perfect with no issue. Am I doing something wrong? emulation.gametechwiki says ares is the best 32x emulator, so why does it play knuckles chaotix so bad compared to kega fusion?

**Comment by remutro** [comment]
Does it indicate in the status bar you are maintaining a solid 50 VPS while the game is running? When audio starts to crackle do you see this slip below 50 VPS? If that is the case, it means the emulator isn't able to keep up in real-time and audio crackle is expected when this occurs. The 32X core is one of the most demanding cores in ares due to the shear number of processors it has to emulate and synchronization that needs to occur so it does require a relatively good CPU in order to run full speed at all times. What CPU do you have in your system? I haven't noticed any audio issues, but I've only made it to the beginning of the fourth zone in testing. 

If you believe you are able to maintain full speed at all times, are there specific areas where you experience this? If there are specific areas, it would help if a save state could be provided (along with ares release version) slightly before where it occurs to see if it can be reproduced. 

It may also help if you could include a screenshot of your Settings > Drivers configuration.

**Comment by goodstuff626** [comment]
![Screenshot (9)](https://github.com/ares-emulator/ares/assets/39889961/197f29cb-87c2-4feb-ac1e-7b9960f52c38)

I'm using windows 10 64bit, i7-6700 CPU @ 3.40GHz   3.41 GHz, while playing it stays around 53-55 vps, but I'm still noticing slowdown, and the crackling audio starts as soon as I load the rom.

**Comment by remutro** [comment]
I don't know why I thought I saw the PAL version originally, my bad. If you are running the Japan/USA region ROM, it is supposed to run at 60 VPS steady. If your system isn't capable of maintaining 60 VPS then you will experience audio stutter because it isn't running full speed. The i7-6700 might not be strong enough to run the 32X core full speed given its speed/age and how demanding this core is. 

With that said, if you can maintain 53-55 CPS on average, that is above the 50 VPS to run the European ROM at full speed, so maybe you want to try that one out and see if it improves? 

You may also want to try to synchronize under audio, and deselect synchronize underneath video. This usually works better.

**Comment by goodstuff626** [comment]
I deselected video sync and enabled audio sync. With both USA & Europe roms the audio crackling was not as bad, but still there. Also the Europe rom was still having slowdowns with the vps around 48-51, and was glitching very badly almost every time I loaded it (the USA rom would also glitch sometimes, but not as frequently). First time Knuckles would disappear while running through first level, then after re-loading the rom it completely froze with the music still playing before I got to the end of the first level. Pic shows where it froze. 

![Screenshot (10)](https://github.com/ares-emulator/ares/assets/39889961/78740ba3-9933-456a-aea5-bfb106368c30)

I did not realize the i7-6700 was not strong enough for 32x on ares. I thought a too slow cpu would just cause dropped frames & slowdowns, would it also cause those game breaking glitches?

**Comment by remutro** [comment]
A CPU that isn't strong enough to keep up shouldn't cause game breaking glitches as far as I'm aware, so not sure why that may be happening. If you have Steam running or something like reshade running at the same time you might want to shut them off to make sure they aren't interfering. I've played about half-way through this game and haven't hit any issues myself personally with crashes/freezes. 

But again the 32X core is one of the most demanding in ares. It takes quite a bit to accurately emulate the M68K processor, Z80 processor, Mega Drive VDP and 32X VDP, and two SH2 processors and keep them all running in sync properly. Adding the Mega CD introduces another M68K processor (clocked 5 MHz faster) so games that utilized both are even more demanding. 

But if you can't maintain 60 VPS for the J/U region ROMs or 50 VPS for the E region ROM then audio stuttering is to be expected when it drops below expected level. 

Definitely not freezing in the E ROM where you did:

![image](https://github.com/ares-emulator/ares/assets/84990500/94ac6c42-cb16-443c-8869-546803587186)

**Comment by goodstuff626** [comment]
Yeah, I didn't have steam or anything else going when playing, just ares. I guess I need to upgrate my cpu lol. Anyway, thanks for the help.

**Comment by ks202005** [comment]
What's your CPU, and what are your Windows power options set to? There's a chance your CPU can run the game just fine if you adjust those power settings. I use a 2600X and have this same issue when using the "Power Saving" preset, but it's totally fine in terms of speed when set to Ryzen Balanced. It has to do with the artificial CPU limitations capping the clock speed of your CPU too much.
