### ISSUE TITLE
Color tinting issues on GBA games.

### ISSUE THREAD

**Issue by randomsomeone69-real** [higan-emu/ares#1470]
**Describe the bug**
The games are looking darker than what they are supposed to be.

**To Reproduce**
1. Load a GBA game
2. Start the game
3. Load the same game, in a another emulator (mGBA is used) or on real console.
4. Compare the pictures

**Expected behavior**
The colors should be like on real hardware.

**Screenshots**
Here's an example of the issue with the AGS aging cardridge.

**Additional context**
![Capture](https://github.com/ares-emulator/ares/assets/160155909/737c4501-44d8-4eec-b4f7-11cbe61599a4)
Here is the side by side comparaison with mGBA. You can see taht the colors are brighter on mGBA. But being on a emulator can also be quite inaccurate. I then used real hardware.
![20240502_124003](https://github.com/ares-emulator/ares/assets/160155909/d431b186-e105-4f63-a1cb-a5149beda2e0)
Here is the same cardridge running on a N2DSXL. You can see that the colors is much closer to the emulator.

Then, I loaded up WarioWare Inc. (Europe) and I saw the same thing.
![Capture2](https://github.com/ares-emulator/ares/assets/160155909/695ad795-d3aa-43ae-aae4-574291f4b071)

Then loaded up the same game on the N2DSXL.
![20240502_125629](https://github.com/ares-emulator/ares/assets/160155909/8da0be41-7ad1-403f-a2d9-ab8350565d36)

By comparing, I think that mGBA is still nearer to the output to the N2DSXL.

So I think that ares has a tinting bug.

**Comment by LukeUsher** [comment]
The DS and 3DS screens are significantly brighter than the original GBA screen and are a poor comparison in this case; it would be better to compare against a real GBA.

If you are unhappy with the tint, you can turn off "Color Emulation" in the ares settings. This will output pure colour rather than attempting to filter to match the original GBA screen.

**Comment by randomsomeone69-real** [comment]
Oh, I didn't know that they have poor comparaisons.

Well, I learned something today. But why the color is brighter on mGBA than in ares? Just curious.

**Comment by Kawa-oneechan** [comment]
> But why the color is brighter on mGBA than in ares? Just curious.

At a guess, because mGBA's image is unfiltered. The white in the WarioWare logo is a pure `#FFFFFF`, which is what's actually stored in the game data (or rather `#7FFF` because it's 15-bit not 24 but that doesn't matter here.) In Ares, with the color emulation turn on, that pure white reduces to `#F6EEF2`, to closer match what you'd see on the notorious GBA screen.

**Comment by randomsomeone69-real** [comment]
Ahh so that's why. So it isn't a bug. My bad, thank you anyways.
