### ISSUE TITLE
SNES roms fail to load on v138

### ISSUE THREAD

**Issue by PaulTGG** [higan-emu/ares#1473]
**Describe the bug**
Trying to load a SNES rom just shows a black screen.  (No audio plays either.)  Ares still appears to be running, as the VPS counter changes.  Ares was built from source on Linux.

**To Reproduce**
1. Open Ares v138
2. Try to load a SNES rom
3. Screen stays black, and the rom doesn't load.

**Expected behavior**
The SNES rom should load and run the game.

**Screenshots**
![screenshot](https://github.com/ares-emulator/ares/assets/12187131/270a4772-125f-4139-a207-df6fdd3b286e)

**Additional context**
SNES roms load without issue in v137.

**Comment by LukeUsher** [comment]
One change in v138 is that the SNES cartridge database is now fetched from filesystem rather than being embedded within the executable; this allows for editing of the database for development/debugging/adding homebrew;

Make sure that the Database directory has been copied to the correct location for your operating system.

If you self compiled, you may have forgotten to run `make install`

**Comment by PaulTGG** [comment]
> If you self compiled, you may have forgotten to run `make install`

Yep, that was it.  Thanks for the help!
