### ISSUE TITLE
[N64] Mario 64 doesn't boot

### ISSUE THREAD

**Issue by nonetrix** [higan-emu/ares#1511]
Before submitting an issue, please use the search to make sure an issue doesn't already exist, you should also make sure your rom is not a bad dump, by comparing against the hashes in the No-Intro (Cartridges) or Redump (CD-ROM) databases.

**Describe the issue**
The game doesn't boot displaying corrupted graphics then repeating audio. I am on NixOS using the package from Nixpkgs, could be a issue on how this is packaged as others are having luck with this but not sure. Also, I am using a Ryzen 7 3700X, and a RX 6800 with the normal Radeonsi and RADV drivers respectively 

https://github.com/ares-emulator/ares/assets/45698918/fd5ada70-0bff-459f-b8e2-db0ac1fce2b5

**Rom Information**
z64 USA version sha256 ` 17ce077343c6133f8c9f2d6d6d9a4ab62c8cd2aa57c40aea1f490b4c8bb21d91` matches https://datomatic.no-intro.org/index.php?page=show_record&s=24&n=0717

**Comment by remutro** [comment]
This is most likely going to be an issue with drivers installed (there are no issues playing Mario 64, or 93% of the library). Does this happen with another system besides the N64 (I would think other cores are fine)? And although ares doesn't create linux packages for distribution and some package maintainers make mistakes excluding some things like the internal DB or shaders, ares itself compiles into a single executable, so it wouldn't be missing components causing rendering issues. 
As ares uses parallel-rdp for the RDP portion of the N64 core, your GPU/drivers have to support an up-to-date Vulkan spec in order for it to work/render properly.  Have you run the 'vulkaninfo' command on your system to see if it reports any errors? Does it say what versions/features your system currently reports?

**Comment by nonetrix** [comment]
It should support most if not all of Vulkan 1.3, I've played a lot of games on Proton with no issue. Even fooled around with RT with somewhat disappointing results, but that's just AMD for you it at least worked. I'll try other cores when I have the time. 

But the packaging being wrong wouldn't surprise my Nix packages things very differently, so it not including Vulkan for example can be a problem because you need to explicitly do that. Also, the GTK theming seems slightly odd in the file picker but could just be Ares (p.s. consider using XDG Portal btw, I prefer KDE file picker)

**Comment by remutro** [comment]
The ares executable on its own contains everything it needs to run, minus our internal game DB and shaders if a package maintainer forgets to include those directories and the shader *.so. Everything else is self contained in the executable. We don't need to ship vulkan anything, everything needed should be present on your system already assuming your GPU and driver have proper support. If you are saying that the package needs to include extra stuff to support vulkan on NixOS (I personally haven't used that distribution, so don't know) then I would report the issue to the package maintainer. The N64 core is the only one that needs vulkan, so if the others work then that is the problem that needs to be solved. 
Also, in regards to theming, you can build ares using GTK 2 or 3, with 3 being the default. But this could be changed by the package maintainer as well (not sure what they would have used to create this package). 
Another option is to just clone the repo and build it yourself. It doesn't take much to build ares, and build instructions are documented in the README in the repo. It may also run better because instead of building to target multiple different types of systems, you can build it specifically to yours.

**Comment by MasterNama17083** [comment]
That happened running on my pc machine, same.

**Comment by nonetrix** [comment]
OS? GPU?!

**Comment by MasterNama17083** [comment]
> OS? GPU?! 

Windows 10 Pro 22H2
Intel HD Graphics 4600

**Comment by dracc** [comment]
That explains it. Your GPU doesn't support Vulkan under Windows.

**Comment by MasterNama17083** [comment]
It seems worked on my another laptop running on the emulator which is parallel-rdp plugin (with vulkan).

**Comment by nonetrix** [comment]
Yeah so it might be NixOS thing then, I'll quickly try another core like I said I would and maybe report it upstream. I've seriously had very similar issue to this when for example `vulkan-loader` wasn't included in Prismlauncher and I tried the Vulkan mod

**Comment by nonetrix** [comment]
Anyway, other cores work fine
![image](https://github.com/ares-emulator/ares/assets/45698918/60dfc660-48d6-4e52-bf2d-cde30cb6b2b0)

**Comment by nonetrix** [comment]
And yep it's Vulkan issue, I think I might know what to do to fix it in the case of NixOS. I'll experiment later
```
♥ ❯ ares
Vulkan init failed: No RDP rendering support
```
I think just have to do same thing as this https://github.com/NixOS/nixpkgs/pull/303880

**Comment by LukeUsher** [comment]
Closing as this is not an ares bug; please see above comments

Something is wrong with Vulkan on your system and/or hardware,

**Comment by nonetrix** [comment]
Fixed in nixpkgs

Edit: Tested it too fixes issues
