### ISSUE TITLE
Saved screenshots don't have the correct dimensions

### ISSUE THREAD

**Issue by eisnerguy1** [higan-emu/ares#1567]
**Describe the bug**
Whenever I take a screenshot, via ares v139 on macOS, the resulting images' dimensions are all messed up.

**To Reproduce**
1. Go to the "Tools" menu
2. Click on 'Capture Screenshot', or press the hotkey "`"
3. Open up the screenshots folder "/Users/eisnerguy1/Library/Application Support/ares/ScreenshotsNintendo 64", as an example on macOS
4. See the odd saved screenshot dimensions.

**Expected behavior**
The saved screenshot should have normal dimensions, like 4x3, not stretched out like my examples below show.

**Screenshots**
![F-Zero X (USA) 2024-07-14 15-10-19](https://github.com/user-attachments/assets/29fc8287-159d-49ba-a1b5-942e6aa57808)
![NUD-EFZJ-JPN_LB_sealed 2024-07-15 06-26-38](https://github.com/user-attachments/assets/ddec06f4-b190-456e-8e2f-2a082e93319d)

**Additional context**
Here's what my settings in ares are 
![Screenshot 2024-07-15 at 5 51 53 PM](https://github.com/user-attachments/assets/01a05a24-b524-4c6f-b89a-d48d6a2d2db5)
![Screenshot 2024-07-15 at 5 52 03 PM](https://github.com/user-attachments/assets/812f4d16-42ba-4a6e-81d3-9b2a0c8cfad1)
![Screenshot 2024-07-15 at 5 52 06 PM](https://github.com/user-attachments/assets/95f3ff2f-68f2-41ef-9f9f-d4af8e401818)

I've even tried to make sure all of the scaling options are 1:1 pixel perfect:
![Screenshot 2024-07-15 at 7 12 27 PM](https://github.com/user-attachments/assets/d9918166-c65d-4beb-9f87-b32c79cf8c0b)
![Screenshot 2024-07-15 at 7 12 34 PM](https://github.com/user-attachments/assets/8432b59e-1dbb-4f97-942f-87cfe8e564bc)
![Screenshot 2024-07-15 at 7 12 39 PM](https://github.com/user-attachments/assets/05872115-38d3-4a18-b922-a7fca6ed86ae)

Am I missing something super obvious? Any help at all would be greatly appreciated! 👍🏻

**Comment by Screwtapello** [comment]
This is behaving as intended.

If you want a screenshot of the game's output after things like shaders and aspect-ratio correction have been applied, you can use your operating system's built-in screenshot tool. The internal "save screenshot" feature captures the actual pixels the console produces, in whatever aspect ratio it produces them.

This often produces surprisingly wide screenshots, because although it's impractical to change the number of *rows* of pixels output (when connected to a standard standard-definition CRT TV), it's very easy to change the number of *columns* and consoles did, frequently.

I'm not sure exactly what the deal with the N64 was, but for the SNES games could present 256 pixels per scanline, or 512 pixels. Worse, they could switch between those two resolutions *per scanline*, not just per-frame. The emulator must set aside space to store the frame as it's being rendered, and since it doesn't know how wide the frame will be before it's rendered, it picks the maximum size just to be safe. As a result, even if the SNES is showing a 256×240 image, ares' internal screenshot tool will produce a 512×240 screenshot.

(As aside, the Mega Drive is even worse off—its two resolutions are 256px and 320px, so to make sure both resolutions can fit neatly in the same image, it produces 1280x240 screenshots)

**Comment by eisnerguy1** [comment]
Ah, gotcha. Thanks for the clarification 😄  I kinda managed to get 1:1 pixel screenshots with some trickery so, this can be closed 👍🏻
