### ISSUE TITLE
runahead: performance difference between Windows and Linux 

### ISSUE THREAD

**Issue by petran79** [higan-emu/ares#1677]
I decided to dual boot, since W10 is so boring as an OS and so I installed Opensuse Tumbleweed.

My system is an old but still good i7 4790k stock cpu and Nvidia gtx 1080.

I had Ares on W10 first and I noticed that whenever I enabled runahead, games would sink to 45 fps, no matter the sound driver.

I compiled Ares on TW (sdl, librashaders, gtk3 enabled) and noticed that when I enabled run-ahead, games would still retain 60 fps with some occasional pop-ups. To ensure it was activated, I restarted Ares after enabling it. This under Plasma and Wayland. Games played fine with that option. Whether with sdl or alsa sound drivers, no matter the latency.

To make sure it wasn't just some Linux magic, I also tested run-ahead on Mesen and sound would start to crackle on both OS at the same value (6 ms and above)

Is it possible to confirm if this issue exists on other W10 systems too and if it could be patched

**Comment by LukeUsher** [comment]
All libco bases emulation core (that is currently everything except n64 and ps1) are slower on windows and it’s unavoidable. 

This is because the win64 abi requires more state to be saved and restored on context switches than the SysV ABI used in Linux/unix systems, making context switches more expensive on Windows systems. 

You can close the gap by modifying libco to prevent backing up and restoring SSE registers, but this breaks assumptions made by both the compiler and operating system so it will cause instability and/or data corruption, sometimes so subtly you may not notice; but it is an unsafe configuration. 

For the curious: you can see how much more code it takes to context switch safely on windows here: https://github.com/ares-emulator/ares/blob/7e5292cd1675e1947f18ec47146690ef5129e2f5/libco/amd64.c#L20
