### ISSUE TITLE
[n64] black screen

### ISSUE THREAD

**Issue by modman123456** [higan-emu/ares#1699]
every n64 rom file i try to run it just shows a black screen it runs but i cant see i can hear the sound but nothing and wen i tryed sm64 it glich out and crashes all other game consoles work but this does not work on all versions of ares that dont crash on lanch
![Screenshot 2024-11-17 180412](https://github.com/user-attachments/assets/55ad5271-8d6b-4552-9e23-234e85b59d6a)
os window 11

**Comment by remutro** [comment]
The N64 core makes use of parallel-rdp for its RDP implementation, which means your GPU has to support Vulkan (version 1.1 if I'm not mistaken). Make sure you have updated your GPU driver. What do you currently have for a GPU, and what is your driver version?

Also note that this has nothing to do with driver selection in Settings > Drivers. The selections there are only used for posting an image to your screen and otherwise to involve rendering in-game. But in order for the N64 core to work, you have to have a CPU/driver with proper Vulkan support. I would imagine if ares is having an issue, Simple64 would also have problems which may be a worthwhile test to validate Vulkan support on your system.

**Comment by modman123456** [comment]
yep i think i is Vulkan i dont know how to update my drivers but simple64 did not work i dont even think it loaded the rom this time
![image](https://github.com/user-attachments/assets/827a0387-0f55-49d9-b801-ab6512b923d6)
hears my driver i think. i fond a file from 2022 so that could be the last time it got updated or it was never updated
![image](https://github.com/user-attachments/assets/506e9617-2d89-412b-9ecb-84f07ea5e15f)

**Comment by modman123456** [comment]
nvm i just updated my drivers with nvidia app and it still does not work im just going to do this on a raspberry pi

**Comment by remutro** [comment]
That card should support vulkan. Does your system have an iGPU besides your nvidia card? It might be getting mixed up with that. Check in Windows Device Manager and if you see an additional graphics device, try disabling it and just leave your nvidia card enabled and then try running an N64 game in ares again. 

I hope you at least have a raspberry pi 5 if you are going to attempt running N64 games w/ares on it. I can't say for sure if it will work well or not on a pi5 and I haven't heard of anyone else trying but there is no way a pi4 would work. The N64 core is one of the most demanding cores in ares. You'll need a reasonably good CPU to run it at full speed for all games.

**Comment by modman123456** [comment]
thank you it worked it sed openGL 3.2 did not work but but direct3d works thank you now i can make n64 games

**Comment by modman123456** [comment]
thank you it worked it sed openGL 3.2 did not work but but direct3d works thank you now i can make n64 games
