### ISSUE TITLE
[feature request] support for libretro shaders

### ISSUE THREAD

**Issue by AbreuEfechou** [higan-emu/ares#182]
please add support for .cg and .cgp shaders 
https://github.com/libretro/common-shaders

**Comment by Screwtapello** [comment]
The .cg shader format requires the [NVIDIA Cg Toolkit](https://developer.nvidia.com/cg-toolkit), a legacy no-longer-supported library, so it's unlikely to ever be supported. However, hunterk of RetroArch has kindly ported a bunch of shaders to the Quark format used by ares/higan/bsnes: https://github.com/hizzlekizzle/quark-shaders/

**Comment by LukeUsher** [comment]
It's worth noting that I now include all license-compatible shaders from quark-shaders in new releases, however, the GPL shaders are not license compatible with ares' ISC and are not bundled.

**Comment by AbreuEfechou** [comment]
> It's worth noting that I now include all license-compatible shaders from quark-shaders in new releases, however, the GPL shaders are not license compatible with ares' ISC and are not bundled.

don't need to bundle them, just support them and the user install the ones which they like

**Comment by LukeUsher** [comment]
As much as people would like this feature, unfortunately, I'm going to mark it as a "won't fix".

cg/cgp shaders will never be supported due to their reliance on NVIDIA CG, which has been discontinued since April 2012, I don't think it's a good idea to import a huge dependency such as the CG toolkit in the first place, especially not when it has not been officially supported for almost a decade.

**Comment by ceed0** [comment]
I wanted to bump this issue to see if there's interest in using new [librashader](https://github.com/SnowflakePowered/librashader) library.
To be clear, it's not about cg shaders, but modern [slang-shaders](https://github.com/libretro/slang-shaders).
