### ISSUE TITLE
[M-CD] Arcus I, II, III: Hangs in green screen before enters in main menu

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#216]
The screen basically says that the Mega CD couldn't load the game and asks to try to reset the game
![image](https://user-images.githubusercontent.com/12163923/135762683-c7ddb536-42e4-4fce-ba13-d9365f3f6d1a.png)

**Comment by TascoDLX** [comment]
Pretty sure it says backup ram is not initialized and gives instructions to format it via the system's "option" menu. If this screen appears, verify that Mega-CD backup ram has been initialized (ares does this automatically on first boot) and that it's not already full.

Be advised, in its current state, ares maintains only a single shared backup file for the system. So, you may need to manage it outside of ares if you intend to preserve more than a few saved games. Otherwise, just format it periodically to restore full capacity.

**Comment by LukeUsher** [comment]
Closing this as it is not a bug; the game is just telling you backup ram has not been formatted, and that you should do so in the Mega CD bios; the same thing would happen on real hardware when backup memory isn't formatted
