### ISSUE TITLE
[General input] You can't assign mouse movement as an input

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#224]
This is further worrying as you can't use your mouse to simulate SNES mouse (or any kind of gun such as The Justifier).
Also, when tried to set the mouse X/Y to analog X/Y in the Xbox controller, the crosshair symbol on the screen simply disappears - Is this implementation incomplete?

**Comment by remutro** [comment]
@Shideravan - I'm not sure about other games, but this works for Mario Paint properly. The setup is kinda funky though and non-obvious. 

- Open Settings > Input
- Super Nintendo > Controller 1 > Set "Mouse" from third dropdown menu
- In order to set inputs for X/Y axis and left/right buttons, you need to right-click each option and select the appropriate input to set mouse input
- Open Settings > Hotkeys, there is an option to toggle mouse capture. Pick a key from the keyboard ( I used 'm' ). 
- Load Mario Paint
- From Super Famicom > Controller 1 menu item,  select the "Mouse" option
- With all of the above setup and the Mario Paint running, hit the hotkey you set for mouse toggle ('m' if using my example), and the mouse should work in-game. Hit the mouse capture hotkey again to resume using the mouse to interact with ares

**Comment by Shideravan** [comment]
Thanks for the info. Does justifier working as it should too?
The game manual says that I need to put the gun in second port (the first, just a normal controller), but the crossair for the emulated Justifier just appear if I put in first port. And I can't pass the "adjust aim" screen
![image](https://user-images.githubusercontent.com/12163923/136722747-01813fd2-6166-41a6-8887-dc2335019c58.png)

**Comment by Shideravan** [comment]
In BSNES the crosshair appears, but I'm unable to "pierce the screen" when shooting as it should (the shoot button is working in both emulators, just doesn't seem to be shooting at the target)
![image](https://user-images.githubusercontent.com/12163923/136722991-9f31210f-ad62-427e-9a08-115f37afa9f4.png)

**Comment by remutro** [comment]
Sorry, I'm not really familiar with Mega Drive/Light Gun games. I don't think this has been implemented, as the only options for Mega Drive games I currently see is standard controller and the 6 button fighter stick. I don't see any mouse <> light gun options. I'm not sure that the mouse option works beyond the SNES. Perhaps someone else knows. I remember when Near posted that mouse controls were added and working and it was specifically targeted at the SNES. I don't think it was intended to work anywhere else.

**Comment by Shideravan** [comment]
> Sorry, I'm not really familiar with Mega Drive/Light Gun games. I don't think this has been implemented, as the only options for Mega Drive games I currently see is standard controller and the 6 button fighter stick. I don't see any mouse <> light gun options. I'm not sure that the mouse option works beyond the SNES. Perhaps someone else knows. I remember when Near posted that mouse controls were added and working and it was specifically targeted at the SNES. I don't think it was intended to work anywhere else.

err... I was talking about Lethal Enforces for SNES, that's why I was comparing with the BSNES emulation. But ok.
