### ISSUE TITLE
[PCE] 6 Button Gamepad Support?

### ISSUE THREAD

**Issue by pan-asian-wok** [higan-emu/ares#365]
Forgive me if this is a user error on my part, but I cannot configure 6 button gamepads for PC Engine in games such as Street Fighter II: Champion Edition. I have tried both the nightly builds for Windows 10 and the ares-emu-git build from AUR in Manjaro Linux.

I do notice that I can selected Avenue Pad 6 in the Controller Port 1, but I am unable to select it within Input. I'm not sure if that tidbit is helpful, but I have attached pictures to help visualize the situation.

![Avenue Pad 6](https://user-images.githubusercontent.com/45274474/154644422-2bf7c950-e5eb-4431-889d-a99b53c61503.jpg)

![No Avenue Pad 6](https://user-images.githubusercontent.com/45274474/154644432-d3582e63-d401-4cc2-a902-98a762ee1e36.jpg)

**Comment by LukeUsher** [comment]
Fixed as of [80c2678](https://github.com/ares-emulator/ares/commit/80c267893076e1a74ed76721a582d64a66e44fad)

The issue was that the emulator implements the 6-button controller, but no mapping was provided for connecting the virtual pad to it.

You may have to remap your 2-button PC-Engine controller though, as I have swapped some of the mappings around for consistency with the 6-button pad.

Tested and working with 240p test suite.
