### ISSUE TITLE
[MEGADRIVE] Pier Solar and the Great Architects (World) Freeze on startup

### ISSUE THREAD

**Issue by Yotamtamtam** [higan-emu/ares#374]
Emulator : Ares 1.26 Nightly build (18.02.22)
System : Megadrive / Genesis
Game : Pier Solar and the Great Architects (World) (En,Es,Pt) (Reprint B) (Aftermarket) (Unl)
Database: No-Intro: Genesis (v. 20210226-213851)
File/ROM SHA-1: 2E7710B1956514C27BE24DB000E60D3C3A1DC2D8
File/ROM CRC32: DFB94F1B

For some reason running the game requires the use of Mega-CD BIOS.
Once the BIOS is selected, ares manages to run the game.
Despite this the game freezes on the opening screen.
See attached image
![ARES2](https://user-images.githubusercontent.com/87193210/154737181-bcf80adc-2855-4acd-8ea1-f300680a5cac.png)

**Comment by LukeUsher** [comment]
This game asks for the Mega CD bios because it is a cartridge game that can make use of Mega CD hardware; if the Mega CD is present, it allows you to use an accompanying CD-ROM to get a CD-quality soundtrack. 

As for why it hangs; this game currently uses a custom rom mapper that is not emulated yet, it is not a standard cartridge

**Comment by BiZkViT96** [comment]
This is a duplicate of this #158 from September 6, 2021. And @LukeUsher you've already explained there why the game doesn't load.

**Comment by Yotamtamtam** [comment]
Closes due to duplication
