### ISSUE TITLE
ruby: GDI backend incorrectly handles internally scaled resolutions

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#376]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : Deadly Moves (USA)
System : Megadrive / Genesis

![image](https://user-images.githubusercontent.com/12481242/154798157-e9c8de2b-d2f0-4706-b8d2-14e4beb9c975.png)

**Comment by BenjaminSiskoo** [comment]
Here another example with DJ Boy : 

![image](https://user-images.githubusercontent.com/12481242/154798894-03143c19-d78a-4128-b618-e05bec70a3c6.png)

**Comment by FitzRoyX** [comment]
I can't reproduce this. Try Direct3d and OpenGL and try updating your gfx drivers.

**Comment by BenjaminSiskoo** [comment]
Ok my drivers are always updated.

I was on GDI by default. With Direct3D no problem. Do I close this BR or need to fix GDI before ?

**Comment by FitzRoyX** [comment]
It appears to be an issue with the GDI renderer when the resolution is internally scaled. It's not exclusive to these games, but any game that uses 256x224 vdp mode instead of 320x224. Ares is forcibly stretching the lower mode to 4:3 even with aspect correction setting off. I think not doing that would fix the problem.
