### ISSUE TITLE
Add basic build instructions?

### ISSUE THREAD

**Issue by mariomadproductions** [higan-emu/ares#521]
Even if its just "cd into desktop-ui and run make", it'd probably be a good idea to put that somewhere.

**Comment by rasky** [comment]
Given that it's just "make", do we really need to write that?

**Comment by Shideravan** [comment]
> Given that it's just "make", do we really need to write that?

I really think so

**Comment by Kawa-oneechan** [comment]
Is it really just "make" though? I had to jump through some pretty specific hoops to get a build environment set up from which I could just "make".

**Comment by rasky** [comment]
Which hoops?

**Comment by bigbass1997** [comment]
It's not nearly as simple as _just_ running make. Although it's easier than it used to be, it's not necessarily that simple. Either way, is there a negative to putting some instructions in the readme?

For people who have never needed to build something manually on their system before, and potentially even if they have, they may not have all the necessary packages. It's not that uncommon to find readme's that list what packages are necessary. However, to test this, I spun up a fresh VM (Ubuntu 22.04 LTS Beta Server with KDE Plasma).

Ran into a series of failed build, each more confusing than the last. With some googling and searching through `apt` and `apt-file`, I managed to find all the right packages. `make g++ pkg-config libgtk2.0-dev libasound2-dev`. Also needed something that provided OpenGL files, presumably mesa or some equivalent would work, for this I used `libgl-dev` (vendor neutral package). After that, I managed to successfully build and run ares.

Additionally, it'd be nice if the different configurations were mentioned in the readme too. Like how to change between accuracy and performance modes, and how to specify which cores to build. Also it'd be helpful to say how to start ares after building, because that's not obvious to people who haven't run it before.

**Comment by Kawa-oneechan** [comment]
> Which hoops?

Compiling in Windows, I needed a _very specific_ compiler distribution. You'll find that [higan.readthedocs.io](https://higan.readthedocs.io/en/stable/install/windows/#compiling-from-source-on-windows) recommends one right there, but when I tried that it didn't work as required things were straight-up missing.

(I know this is *higan* readthedocs but I was in fact trying to compile bsnes, bear with me here.)

What I *actually* needed was a mingw-w64-install.exe that I can barely even find a download link for ([but I did eventually](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download)), that I then had to re-install with different settings (i686-win32-dwarf) because those had to be very specific too, and *then* I could finally build me a bsnes.

_And even then_ I had to work around some more stuff.

So no, it's not just "make".

**Comment by mariomadproductions** [comment]
Good point, I just happened to have the relevant packages installed already.

**Comment by shinra-electric** [comment]
Also good to mention that the resulting binary is in `ares/desktop-ui/out`

**Comment by remutro** [comment]
For Windows builds, if you just install MSYS2 and follow the instructions on their homepage, you are good to go with the build:

https://www.msys2.org/

**Comment by Kawa-oneechan** [comment]
> just

And you jinxed it.

**Comment by rasky** [comment]
I think people coming from different backgrounds have different, reasonable expectations. I've been compiling C++ programs on different platforms for many years and Ares for me is so straightforward that for me, zero instructions suffice. I agree after reading this issue that zero instructions are not sufficient for everybody.

After discussions with @LukeUsher, we feel that listing Linux dependencies (on common distributions) is a good middle ground, at least for the Linux platform. For Windows platform, a suggestion to use MSYS2 might be OK as well. 

Obviously this will be not enough for all possible people (Should we explain how to git clone? How to install git? How to install make? How to cd into a directory? How to open a terminal?), but it might be a reasonable compromise.

Anybody is willing to write a PR for that, after having verified on a clean machine that the instructions are working and are sufficient?
