### ISSUE TITLE
[N64] Donkey Kong 64 freezes before rap intro

### ISSUE THREAD

**Issue by kev4cards** [higan-emu/ares#539]
Donkey Kong 64 freezes before the rap intro. Offending commit: e98a313 (DIV/MULT opcode timings; also causes the Diddy Kong Racing corrupt controller pak screen in issue #415 ). Compiling without this commit still produces the flickering behavior with the audio lagging behind the visuals as mentioned in the general N64 compatibility issue.

**Comment by Shideravan** [comment]
Fixed in https://github.com/ares-emulator/ares/commit/91f3dfaf3d0a56d691f2da3ad925789ce78e067c

**Comment by ExperimentT** [comment]
I can confirm as of  4989215 this does reach ingame successfully. However, the games speed is wildly inconsistent, with the introduction, menu's and minigame area's running far faster than normal. However, overworld and main world area's are running at the correct speed, including the intentional slowdown absent in other N64 emulators. The graphics however are constantly flickering throughout and displaying Z-ordering issues.

**Comment by kev4cards** [comment]
Just in case if the difference matters down the road, 329a8c9 is the commit that worked for me. With that said, a local build difference could have resulted in this alternate working commit.

**Comment by kev4cards** [comment]
Closing. Will open a new issue if the fix for #14 does not correct the game's problems.
