### ISSUE TITLE
gamepads conflicts

### ISSUE THREAD

**Issue by nanitaro** [higan-emu/ares#554]
Hi!
I would like to report: When configuring gamepads from different consoles, the settings conflicts, not being separate one setting for each console.
Because of this, every time I start a game on a different system, I need to change the controls.

In others, RetroArch allows you to set controls for each core and each game.

Thanks.

**Comment by LukeUsher** [comment]
This is mostly by design: ares is designed that you setup one virtual pad mapping, and then that gets automatically mapped to every emulated system

**Comment by nanitaro** [comment]
I think there is a problem with the automatic mapping function.
For example, would you like to use an left -thumb-stick as a D-pad on SNES?
I would want to use a hat switch.
But if I set the virtual pad like this, it wouldn't be compatible with the N64 system.
It seems that a system without an analog stick needs a function like assigning a hat switch(e.g. L-Up,L-Down) to the D-Pad.

**Comment by LukeUsher** [comment]
> I think there is a problem with the automatic mapping function.
> For example, would you like to use an left -thumb-stick as a D-pad on SNES?
> I would want to use a hat switch.
> But if I set the virtual pad like this, it wouldn't be compatible with the N64 system.
> It seems that a system without an analog stick needs a function like assigning a hat switch(e.g. L-Up,L-Down) to the D-Pad.

This can be done already. There is an up/down/left/right mapping that is separate from l-up/l-down/l-left/l-right. Non-analog systems will use up/down/left/right mappings and analog systems will use l-up/l-down/l-left/l-right; this is how I have it configured at home

**Comment by nanitaro** [comment]
I mapped a left -thumb-stick to up/down / left/right.
I mapped a hat switch to l-up / l-down / l-left / l-right.
![virtual_gamepad](https://user-images.githubusercontent.com/50589546/168440909-d0213a2c-b3f5-47f0-90d3-436cfb401cd9.png)

In the SNES system, left -thumb-stick is mapped to up / down / left / right.
Hat switches are not mapped.
In a non-analog system, what about using the l-up / l-down / l-left / l-right( hat switch) mapping?
![snes_gamepad](https://user-images.githubusercontent.com/50589546/168440921-9eb2eb2c-97fd-47a9-b86f-1ee1cc77c229.png)

**Comment by LukeUsher** [comment]
> I mapped a left -thumb-stick to up/down / left/right. I mapped a hat switch to l-up / l-down / l-left / l-right. ![virtual_gamepad](https://user-images.githubusercontent.com/50589546/168440909-d0213a2c-b3f5-47f0-90d3-436cfb401cd9.png)
> 
> In the SNES system, left -thumb-stick is mapped to up / down / left / right. Hat switches are not mapped. In a non-analog system, what about using the l-up / l-down / l-left / l-right( hat switch) mapping? ![snes_gamepad](https://user-images.githubusercontent.com/50589546/168440921-9eb2eb2c-97fd-47a9-b86f-1ee1cc77c229.png)

You mapped them backwards L-Left means “left stick left”, you have mapped dpad to sticks and sticks to dpad

**Comment by FitzRoyX** [comment]
If I'm understanding this correctly, you want the LSTICK to act as an alternate method of controlling stickless DPAD controllers, without interfering with stuff like the N64 that has both.

I agree that this is how it should work, but the "set your own multi-bindings" stuff gets in the way of that. This was a late feature addition that I think is of dubious value and could probably be removed to allow this.

**Comment by nanitaro** [comment]
OK.
It turns out that it is not possible to have a non-conflicting gamepad setting on the SNES and N64.
Every time I switch systems, I decide to change the gamepad settings.

Thanks.

**Comment by ghost** [comment]
I understand that this is not really a issue, and that the philosophy of the ares emulator is to be as succinct as possible, but i really believe that it would be an amazing feature to at least be able to save and load control profiles just like in cxbx- reloaded. It would be something that would facilitate the possibility of trying out the many games that the different systems have.
Ares has been making very good gains, i migrated from retroarch to ares for its simplicity and good functionality, i had said in this issue that i opened https://github.com/ares-emulator/ares/issues/11 that i would clean and keep using retroarch but i didn't adapt because i don't like retroarch like ares, to update ares is much easier, faster and the experience of playing i think it's better in ares nowadays. I tried to use the antimicro software to have different control profiles to use in ares but it didn't work very well the possibilities are very limited, so the different Marios (Bros... World... Land) or different Donkey Kongs (1,2 and 3) have different settings of running and jumping, something that confuses me, necessitating switching buttons in the controls menu. I hope you will consider this possibility of control profiles at some point. But if it doesn't, that's ok, i'll keep using this great emulator until some other possible alternative (other than retroarch) appears.
