### ISSUE TITLE
[N64] Donkey Kong 64 no longer boots

### ISSUE THREAD

**Issue by kev4cards** [higan-emu/ares#605]
As first noted by rasky, all three regions of Donkey Kong 64 no longer boot as of commit 57b4d68.

**Comment by invertego** [comment]
Here is the root cause analysis I did last year.

> I'm looking at the regressions in DK64 and Banjo-Tooie caused by PI DMA being slowed down by a factor of 4x.
And in the case of DK64, it looks like a pretty straightforward race between a PI DMA of 0x100000 bytes and this loop running on the RSP:
```
1e4  lui     a1,$0020
1e8  bltz    a1,$258
1ec  mfc0    v1,SP_SEMAPHORE
1f0  bne     v1,0,$1e8
1f4  subi    a1,a1,$1
```
 
> If the bltz is taken (after 0x200000 loop iterations) before the PI DMA is done, there's no recovering from it.
During this time the CPU is spinning on the PI DMA, after which it releases the semaphore.
So basically... either this loop is consuming at least 6 RSP cycles per iteration, or PI DMA is a lot faster than it is currently implemented in ares.

```
X * 3 * 0x200000 > Y * 2 * 0x100000
X = RSP cycles per loop iteration
Y = CPU cycles per byte during PI DMA
```

Thanks to @rasky we know the timing on real hardware: X = 7 and Y = ~18. Again, thanks to rasky, ares emulates PI DMA timing quite well. However, it does not accurately track RSP cycles when pipeline stalls must be taken into account (in this case due to the mfc0 and bne instructions).

**Comment by LukeUsher** [comment]
Some additional info, provided by Rasky on the ares discord server

> there are two things that need to be implemented in the RSP interpreter/recompiler for the DK64 boot to succeed:
> * taken branches must have 1 cycle penalty. This should be ~easy to implement on both the interpreter and the recompiler
> * mfc0 must have 3 cycle latency with stall. The code in the 6105 bootcode (used by DK64) does a mfc0 immediately followed  by a use of the register, so this must incur in 2 cycle stall. 
> 
> implementing both will make the dk64 bootcode slow down enough to lose the race with PI DMA, which is what happens on real hardware 
> 
> notice that this might have side effects on the RSP emulator, as effectively we are implementing two slow down behaviors  and our RSP is already slower than the real hardware because we are ignoring the pairing optimization between VU and SU; so I don't know if just doing the above would then have other side effects where the RSP is too slow for some games
