### ISSUE TITLE
[SNES] Feature - HD mode 7?

### ISSUE THREAD

**Issue by Zerowalker** [higan-emu/ares#627]
I am not sure if this is proper to ask for as it's not something that's accurate.
But seeing as there are some enhancements available and i can't find this asked about i will give it a try.

I arrogantly request if it's possible to implement HD Mode 7 as seen in https://github.com/bsnes-emu/bsnes

**Comment by Kawa-oneechan** [comment]
It is not, in fact, appropriate to the ares project to have bsnes' HD Mode 7.

**Comment by Zerowalker** [comment]
Make sense, was just me giving it a shot just in case.

In my ignorance may i ask why that's not appropriate compared to the N64 render settings?
Not trying to nick pick, just actually wondering.

**Comment by Kawa-oneechan** [comment]
_Not in a position of authority here_ but if I had to guess I'd say it's because the N64 is inherently a 3D-only system (by which I mean that 2D screens are just 3D with equal depth), with positions given in floating point, converted to whatever the screen resolution happens to be (usually low res, but expansion pack games would often allow higher).

With a 2D game system like the SNES, increasing the screen resolution would just make each pixel appear bigger, and effectively nothing changes. With a 3D system like the N64, you give the same triangle (same as in it has the same floating-point position data as before) more pixels to cover, drawing a finer line on the edges.

**Comment by Zerowalker** [comment]
Yeah get the 3D difference, as it's just "rasterize this stuff onto these pixels",
the amount of pixels per say doesn't really "matter", it's just how you display the actual (original) data.

But with the HD Mode 7 it's a direct comparison when it comes to resolution,
as you say increasing a resolution normally in a 2D scenario doesn't achieve anything really,
luckily pixelated art can be increased to just look the same, which can't be done in other cases.

But HD Mode 7 (if i understand it correctly) do the calculations and rasteration at a higher res, as the SNES normally tries to show more pixels in less pixels, which you can bypass with this.

I tried comparing the code and thought i would add it myself as Ares is similar to Bsnes,
but clearly not that similar haha, was beyond me to try to patch it in;P

I will let this feature request be here until one with authority says yes or no just in case.
But i completely understand if it's denied and respect it,
I also appreciate the work you all do so let me just put that out there:)

**Comment by LukeUsher** [comment]
I'm closing this as a 'wontfix': if you want this kind of enhancement, consider using bsnes

**Comment by CartoonFan** [comment]
I know this is currently listed as a "wontfix", but HD Mode 7 honestly looks so good that I'd like to add my support for it as well.

The maintainer of bsnes-hd sounds like he's willing to work with you all, if that's something you want or need: https://github.com/DerKoun/bsnes-hd/issues/111#issuecomment-1101807799

Hope this isn't too bothersome, but I was just about to create an issue for this myself, so... :sweat_smile:
