### ISSUE TITLE
[32X] PWM DMA does not function?

### ISSUE THREAD

**Issue by DevsArchive** [higan-emu/ares#630]
Ran a couple of Chilly Willy demos and tried running my own code that's said to work on real hardware, but it does not function in ares.

**Comment by remutro** [comment]
I'm not sure what you ran exactly (I ran the Spear of Destiny & Wolfenstein 3D demos he made and they seemed to be OK - nothing to really compare it to though). This is likely fixed with TascoDLX's fixes in place. Can you either provide details on what you were running or try with the latest nightly build again and report if it is working or not?

**Comment by DevsArchive** [comment]
To be honest, I completely forgot about this issue, as it is months old. The fixes look to be put into place only just a couple of days ago. The problem was that there was just no sound output (which apparently has to do with a lack of DMA channel 1 implementation at the time). The issue appears to now be fixed after running some stuff.
