### ISSUE TITLE
[GG] ares is setting the region to (J) even when the "prefer USA" is set

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#640]
Take a look at the image. Even choosing the prefer USA option, the game runs as a Japanese version (take a look at the katakana in places names below in the screen)
![image](https://user-images.githubusercontent.com/12163923/180128709-06159b2a-988e-4486-b5a3-fd87bf7916cc.png)

It's valid to mention, that the game used is the same in USA and Japanese regions. The game changes it's version accordly with the Game Gear system.

**Comment by Shideravan** [comment]
As a reference, the game shows "Tails' house" in USA version, as below.
![image](https://user-images.githubusercontent.com/12163923/180128973-101b9ebb-dfbe-4f34-a128-3252980f5e63.png)

**Comment by Screwtapello** [comment]
> It's valid to mention, that the game used is the same in USA and Japanese regions.

Despite the screenshot saying "Tails' Adventures (U)", [the No-Intro database entry for this game](https://datomatic.no-intro.org/index.php?page=show_record&s=25&n=0386) calls it "Tails Adventure (World) (En,Ja)"

**Comment by Shideravan** [comment]
> > It's valid to mention, that the game used is the same in USA and Japanese regions.
> 
> Despite the screenshot saying "Tails' Adventures (U)", [the No-Intro database entry for this game](https://datomatic.no-intro.org/index.php?page=show_record&s=25&n=0386) calls it "Tails Adventure (World) (En,Ja)"

Yes, the game has the same code distributed in both regions. The language changes based in Game Gear itself.
Eg.: Running the game in an American Game Gear, the game shows the text in English. Running the game in a Japanese Game Gear, the game show the Japanese texts.
The issue is, there's no way to play this game in English in present state of the emulator. As even setting "Prefer US" in options, the game behaves as if in a Japanese Game Gear.

**Comment by FitzRoyX** [comment]
This is known and I've raised this issue in the past. Near was attempting to avoid having to manually set the region for Sega games, something I think is unavoidable. The current region selector is not a system dictate like it appears. Rather, you can read every setting as:

"Detect via Rom Bits and if bit = Multi-Region or None, use THIS region"

Well, because these bits are not actually what triggers regional changes, they tended not to marked correctly in the rom. And you end up with lots of situations like this where the bit is marked "Japan" and now you're blocked out of English menus and text. The region flyout should look more like this:

Try Auto
USA
JPN
EUR

The word "Try" is really important here. Just saying "Auto" is going to make people think it's foolproof. You could also say "Guess via Rom" or whatever.

**Comment by LukeUsher** [comment]
The issue here is that ares only implements one variant of Game Gear, and doesn't even know that USA/JAPAN versions are different, see the system list here: 

https://github.com/ares-emulator/ares/blob/3ca1f9ebb4ae3f472f7fba661746058f84126536/ares/ms/system/system.cpp#L5

The solution would be to update ares to emulate Japan and 'rest of world' versions of the game gear.

Unlike the master system, in which games detect region by checking for hardware differences, the game gear has a proper region register located in bit6 of IO port 0, that should be 0 for Japanese systems and 1 for rest of world. Ares does not yet implement this.

**Comment by LukeUsher** [comment]
Fixed as of 9a3d949fc2e50fc0d2fde3092e9b91c1eb202e44
