### ISSUE TITLE
[MD] Aspect correction option doesn't work

### ISSUE THREAD

**Issue by PeterSamuels** [higan-emu/ares#676]
The aspect correction option doesn't work in Ares for the Mega Drive. It always displays at 10:7 aspect ratio, which is square pixels for the 320px mode and overly stretched for the 256px mode (5:4 PAR). The correct pixel aspect ratio for 320px mode is 32:35, and for 256px mode, it is 8:7. Without overscan (which also does not function in Ares' Mega Drive emulator), this is a display aspect ratio of 64:49 (like the SNES).

The examples in the following have three images of 320px mode and two of 256px mode (from Vampire Killer).

Incorrect aspect ratio:
![image](https://user-images.githubusercontent.com/63016614/185198865-de632fec-b43c-4a04-add4-c71f15120c23.png)![image](https://user-images.githubusercontent.com/63016614/185199291-cd6f3f04-34f9-45c7-906a-bbf2e564694d.png)![image](https://user-images.githubusercontent.com/63016614/185199459-78c7225d-b1e8-470a-8fc6-a308468e069a.png)![image](https://user-images.githubusercontent.com/63016614/185200101-f27b3e59-de53-4650-982e-c57c0f3e6ba1.png)![image](https://user-images.githubusercontent.com/63016614/185202359-f02da62d-38d8-4ee1-81c4-b70c94c4fadd.png)

Correct aspect ratio:
![image](https://user-images.githubusercontent.com/63016614/185198993-8287542e-9068-4fef-98a1-33d56e1a0e6f.png)![image](https://user-images.githubusercontent.com/63016614/185199331-3bb51c7e-cad3-4257-88f4-8f5b67fab6ee.png)![image](https://user-images.githubusercontent.com/63016614/185199499-8f2c837d-fdee-42e0-a481-67db98054e26.png)![image](https://user-images.githubusercontent.com/63016614/185200396-66504f37-0100-4442-8e2d-641ce4595df6.png)![image](https://user-images.githubusercontent.com/63016614/185202253-ec0d0dd8-5376-4d09-8858-e2d0c79b0cd0.png)

While not directly part of what this issue is about, I also wonder if it would be desirable to have 256px mode, when aspect correction is turned off, display with square pixels like the 320px mode does (probably with pillarboxing so the window wouldn't change sizes if games switch between modes); in these instances, square pixels cause the logos to match the box.
![image](https://user-images.githubusercontent.com/63016614/185200856-532c3590-18a5-4550-b272-e29e65fe8be0.png)![image](https://user-images.githubusercontent.com/63016614/185202122-10337422-1fa5-44ac-b3cf-40728ceebc0d.png)

**Comment by TascoDLX** [comment]
I think this can be done rather simply by setting AR to 32:35. This will naturally bring 256px mode to 8:7 with no further changes required. Note, 256px mode is always scaled 5:4 horizontally due to the difference in pixel clock. Therefore, you should never see square pixels in 256px mode.

Note, disabling Overscan mode in Ares merely clips the image -- it doesn't affect AR. The setting is only used to enable display of PAL-only lines, not to enable true PAL video display, which probably should be handled internally when running PAL 50Hz (if feasible). I don't know if any other supported systems intend to display striking differences when running in PAL mode, but it's definitely worth reviewing in MD's case.

**Comment by PeterSamuels** [comment]
RE: simply setting to 32:35, I wasn't sure if it would cause problems scaling twice.

RE: Overscan affecting AR, I meant the effective display aspect ratio of the window, and not anything internal.

**Comment by TascoDLX** [comment]
Ok, you said the overscan option isn't working, but I'm saying it should be fine and working as intended. As long as adaptive resize is enabled, the change should be immediate. I don't think we're forcing it when in PAL mode? I can verify later if necessary.

But yes, 64:49 effective is correct. 320x224 * 32:35 == 64:49. It will arrive at the same place. That 32:35 is just 8:7 scaled by 4:5 due to pixel clock difference. It's all good.

**Comment by PeterSamuels** [comment]
By overscan not working, I meant it's always 224 height, at least as far as I can see.

**Comment by LukeUsher** [comment]
fixed a26e1ae00631a976a12f50d6ca6f49e60287d8e5

**Comment by LukeUsher** [comment]
> erely clips the image -- it doesn't affect AR. The setting is only used to enable display of PAL-only lines, not to enable true PAL video display, which probably should be handled internally when running PAL 50Hz (if feasible). I don't know if any other supported systems intend to display striking differences when running in PAL mode, but it's definitely worth reviewing in MD's case.

This is by design: the current overscan feature is poorly named, for most systems it is not overscan, but just hiding the PAL borders. I am considering replacing this with a proper overscan function that does what you would expect (clip the outer edges of the screen by approx 2.5% on each edge)
