### ISSUE TITLE
Z80 LD_a_irr bug

### ISSUE THREAD

**Issue by raddad772** [higan-emu/ares#710]
**Describe the bug**
z80 instructions.cpp
line 353-354:
  WZ = x;
  A = read(displace(WZ));

displace will just return WZ by default. I believe this is meant to be

A = read(displace(x));

I didn't care to make a PR for it though as I'm not 100% sure. It just isn't consistent with every other use of displace()

**To Reproduce**
Look at the code

**Expected behavior**
...

**Screenshots**
...

**Additional context**
...

**Comment by TascoDLX** [comment]
Correct, but this is not the instruction variant using index+displacement, (IX+d) or (IY+d). That one would be LD_r_irr. Note, it is the same case with LD_irr_a vs. LD_irr_r. So, while it is a bit of a misuse, there's no actual consequence for using displace() here -- it's just plain unnecessary.

(Note: I might quietly "fix" this since it looks like I'll be correcting a couple Z80 instruction timings anyway.)

**Comment by LukeUsher** [comment]
Fixed by #723
