### ISSUE TITLE
[FC] Nobunaga no Yabou - Sengoku Gunyuuden (J): hangs eventually, music keeps playing ETROM

### ISSUE THREAD

**Issue by FitzRoyX** [higan-emu/ares#848]

**Comment by encoded-byte** [comment]
This issue is related to MMC5 extra sound channels not working at all on ares. The length counter and envelope are never clocked on the pulse channels, and this game is waiting forever for the length counter to be zero after writing a value to it.
This issue could potentially affect any game which uses MMC5 extra sound channels.
