### ISSUE TITLE
NES [Enhancement] Does it possible to make option for sound... #131

### ISSUE THREAD

**Issue by WhiteMagicRaven** [higan-emu/ares#863]
Just look that great video, explaining on how sound can be enhanced highly
https://www.youtube.com/watch?v=8RrQrATnXXY&t=68s&ab_channel=KYLXBN

**Comment by LukeUsher** [comment]
Unfortunately the goal of the project is accurate hardware emulation; so this this is not planned to be implemented.

MSU style things make it in because they're possible on real, unmodified hardware via flash cart (SNES) or Sega CD (MegaDrive)

But this is something that isn't possible on original hardware, and outside of scope.
