### ISSUE TITLE
[WonderSwan] Mahjong Touryuumon (Japan): Runs faster than it should, missing music/audio

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#879]
**Describe the bug**
Mahjong Touryuumon runs noticeably far faster than it should and is missing audio. Occurs on both Rev 1 and Rev 3.

**To Reproduce**
Start the game and mash through the first few screens. Most obvious with the portrait bobbing on the character select.

**Expected behavior**
I expected the game to run at the proper speed and play audio.

Tested on Ares v130.1 built November 23, 2022
Tested on Linux Mint 21

**Comment by asiekierka** [comment]
Based on Dox's analysis, the game requires at least a minimum level of asynchronous serial port emulation (not actual communication, just acting as if the circuitry was present).

**Comment by asiekierka** [comment]
Based on FluBBa's work, serial port interrupt emulation will get the music playing, but won't necessarily fix the speed.

**Comment by asiekierka** [comment]
https://github.com/ares-emulator/ares/pull/906 should cover the missing parts for the "missing music/audio" portion, but not the "runs faster than it should" portion...

**Comment by asiekierka** [comment]
The "runs faster than it should" issue is caused by the game setting I/O port 0xA0 bit 3 to 1, which - contrary to community documentation and *the ROM header* which have it opposite, means "run the ROM bus at 3 waitstates" as opposed to the default of "1 waitstate". This, combined with the fact the game's code just runs as fast as it can go, with no regard to VBlank, is probably the reason for this issue.
