### ISSUE TITLE
[N64] Enable and Disable Expansion Pak

### ISSUE THREAD

**Issue by ArthCarvalho** [higan-emu/ares#939]
Some games offer additional features with the Expansion Pak turned on and while it is good that it is enabled by default, there could be an option to disable it to test different use cases that is specially useful for homebrew developers, such as testing how the game behaves with different memory configurations.

**Comment by jeffythedragonslayer** [comment]
Where on the UI do you think this option should go?

**Comment by ArthCarvalho** [comment]
I think the Nintendo 64 menu could be a good place for it, since it's N64 specific.

**Comment by jeffythedragonslayer** [comment]
That sounds like a natural place to put it.  Do you have screenshot?

**Comment by Shideravan** [comment]
Specially because some games have a compromised framerate when they enter expansion pak mode on the original console. I do not know why. Probably bad optimization done for expansion pak mode during the development of these games.
Some games even lose the ability to perform some tricks. For example, many people report increased difficulty performing the weapon swap glitch in GoldenEye 007.
So to me, it makes perfect sense to have the ability to remove/replace the expansion pak through a Nintendo 64 options menu.

**Comment by LukeUsher** [comment]
Fixed in #1302
