### ISSUE TITLE
I'd love it if more PlayStation systems were included.

### ISSUE THREAD

**Issue by 1MM0R7AL5** [higan-emu/ares#954]
I've been really interested in games on later experimental systems (namely Persona 3 and 4), and I don't want to pay ridiculous amounts of cash for official ports. I'd enjoy this emulator more if the PSP was added as a compatible system.

**Comment by asiekierka** [comment]
Given the fact Ares's focus on low-level emulation means the N64 requires a high-end computer to run well and the NDS is on hold due to performance considerations... PSP would require a computer from 2032, or so, to run at full speed. You might want to look into PPSSPP, instead.

(Also, ridiculous amounts of cash for official ports? Are the PSP games cheaper?)

**Comment by 1MM0R7AL5** [comment]
I see. I guess there isn't an emulator for everything. Is there an emulator
similar to Ares that specializes in games with those performance
considerations?

**Comment by asiekierka** [comment]
MAME tries to provide the maximum accuracy possible based on the current hardware status quo like Ares, but will make more accuracy trade-offs than Ares would in order to get a given system going.

But you're looking for newer consoles, and in that case... not really, no; there's no project that combines, say, PCSX2, Dolphin, PPSSPP and melonDS.

**Comment by 1MM0R7AL5** [comment]
I understand. I mean, if it *was* possible, I'd probably only play Persona
3 Portable on it anyway. I'll just buy it, then.

**Comment by LukeUsher** [comment]
Closing this; partly because it's a vague request, partly because the creator admitted to only wanting it to avoid buying games; ares is not piracy solution
