### ISSUE TITLE
v118-v131 fail to do anything, no error, no window, just nothing

### ISSUE THREAD

**Issue by garfieldbanks** [higan-emu/ares#993]
**Describe the bug**
v117 runs fine.  See the screenshot below.
v118-v131 just silently fail to do anything.

**To Reproduce**
1. I just double click the ares executable on v118-v131 and it does nothing.

**Expected behavior**
Anything!

**Screenshots**
![image](https://user-images.githubusercontent.com/12904270/221329798-07e109cf-6209-40d0-b6bc-723b39133a73.png)

**Additional context**
Windows 10 Pro x64
Intel Core 2 Duo E4600
4.00GB Dual-Channel DDR2
1024MB ATI Radeon HD 5400 Series

Is there anything I can do to make it print some error out or something?

**Comment by FitzRoyX** [comment]
Try creating a blank text file called "settings.bml" in the ares folder and then running the exe. What happens?

**Comment by garfieldbanks** [comment]
Doesn't seem to have any effect.

**Comment by LukeUsher** [comment]
Your processor is likely too old to run recent versions of ares; the current minimum target is the Nehalem architecture which was released in 2008. 

Your processor is an older generation introduced in 2006 and is not supported by ares. 

You may have some luck if you build the source code yourself; this will optimise for your specific cpu rather than a generic target.

**Comment by jeffythedragonslayer** [comment]
> Your processor is likely too old to run recent versions of ares; the current minimum target is the Nehalem architecture which was released in 2008.
> 
> Your processor is an older generation introduced in 2006 and is not supported by ares.

Could we put a msgbox in that displays an error if someone tries to run ares on an old processor?  I wonder if ares is crashing soon (but not immediately) after startup, because I usually get a blue msgbox error from Windows when I try to run an incompatible executable that won't begin executing at all.

**Comment by LukeUsher** [comment]
> > Your processor is likely too old to run recent versions of ares; the current minimum target is the Nehalem architecture which was released in 2008.
> > Your processor is an older generation introduced in 2006 and is not supported by ares.
> 
> Could we put a msgbox in that displays an error if someone tries to run ares on an old processor? I wonder if ares is crashing soon (but not immediately) after startup, because I usually get a blue msgbox error from Windows when I try to run an incompatible executable that won't begin executing at all.

This isn’t possible, the executable won’t start because your processor doesn’t support it, there’s nothing we can do to detect it at run time because it never runs.  That blue message box is generated by windows when a 32bit application or arm64 application is attempted to run x64 windows, but this is not the case here.

**Comment by jeffythedragonslayer** [comment]
In that case, I think it is bad that Windows is not displaying the blue msgbox.  I'd expect the OS to at least be able to load the exe file off of the disk in this case but it's not clear from this bug report where things go awry after that.

**Comment by LukeUsher** [comment]
> In that case, I think it is bad that Windows is not displaying the blue msgbox. I'd expect the OS to at least be able to load the exe file off of the disk in this case but it's not clear from this bug report where things go awry after that.

It’s because windows doesn’t know. The exe is loaded and starts executing, but crashes due to using instructions the processor doesn’t support, but it crashes so early we can’t show any messages or run any emulator code. As far as windows is concerned it started.

**Comment by LukeUsher** [comment]
We could optimise for older cpus instead of newer ones, which would allow it to work but that causes a performance regression for anyone using newer CPUs. For an emulator that is very resource intensive, 2008 is already a very low cut off date.

**Comment by jeffythedragonslayer** [comment]
I'm not suggesting we optimize for older CPUs.  Just curious where exactly the crash happens.  Like before the WinMain stack frame is setup?

**Comment by LukeUsher** [comment]
> I'm not suggesting we optimize for older CPUs. Just curious where exactly the crash happens. Like before the WinMain stack frame is setup?

Last time we got a crash log in this situation it crashes while setting up the gui. 

But we can’t be sure of where the compiler will spit out newer instructions when optimising, so anywhere we could put detection is unreliable. 

As for why windows doesn’t show the blue message? That’s only shown when the exe header suggests a different architecture than your version of windows supports; in this case it’s an x64 binary on x64 windows, so that case is never hit.

**Comment by jeffythedragonslayer** [comment]
Not enough granularity, I see. :/

Does ares use whole program optimization?  All you need to do is disable them at the entry point.

**Comment by LukeUsher** [comment]
> Not enough granularity, I see. :/
> 
> Does ares use whole program optimization? All you need to do is disable them at the entry point.

It’s a lot of effort especially considering self compiled builds optimise for your specific cpu rather than a generic target; so we’d also need multiple code paths depending on build environment; this user could run ares (perhaps with poor performance due to cpu age) if they compiled it from code. 

In all honesty I’d advise using other emulators in this situation. Ares is very cpu intensive and a high end Ryzen machine only just manages full speed in some of the more complex cores (I’m looking at you 32x), a 2008 cpu is not going to be a good experience.

**Comment by garfieldbanks** [comment]
I installed msys2 using chocolatey and followed the instructions on the main page. For some reason gcc wasn't installed using the command from the main page so I had to install that too. Then I ran the below command. It doesn't seem to be able to detect the msys2 environment in windows.
![image](https://user-images.githubusercontent.com/12904270/221406733-b87f9cd2-9492-4751-8687-1733fb1c85b8.png)

**Comment by garfieldbanks** [comment]
I think what I might be missing is how to enter the MINGW64 environment. Right now my just says MSYS. So maybe that's the problem.

**Comment by garfieldbanks** [comment]
I think what I might be missing is how to enter the MINGW64 environment. Right now my terminal just says MSYS. So maybe that's the problem.

**Comment by LukeUsher** [comment]
> I think what I might be missing is how to enter the MINGW64 environment. Right now my terminal just says MSYS. So maybe that's the problem.

You can select your environment when launching msys:

![image](https://user-images.githubusercontent.com/740003/221407203-b194bc6d-5056-4784-96b0-bb89371eac1f.png)

**Comment by garfieldbanks** [comment]
I found the mingw64.exe in C:\tools\msys64.

It's building now! I'll let you know what happens!

**Comment by garfieldbanks** [comment]
Should I expect this to take an hour or something?

**Comment by garfieldbanks** [comment]
OK it failed:
![image](https://user-images.githubusercontent.com/12904270/221408864-8f42a3c6-bce8-463a-b4be-03fec9daa391.png)

**Comment by LukeUsher** [comment]
Friendly reminder that this issue isn't for build support, and that every watcher of this repository gets notified every time you post; you're generating a lot of notifications here. 

The failure appears to be because you started building in the msys environment before switching to the mingw environment; running a `make clean` first to start a new built should sort you out.

For further support with this, please move to discord to stop clogging up notifications here.

I will close this issue; as there isn't really a bug; just a computer that doesn't meet our minimum target.

**Comment by garfieldbanks** [comment]
After compiling ares on the computer itself following the instructions on the main page, the old computer is able to use the generated exe to run the emulator just fine. SNES runs at 60fps and 32X runs at 25fps.
