### ISSUE TITLE
Ares isn't syncing in video with OpenGL driver (Direct3D is normal)

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#995]
**Describe the bug**
Ares isn't syncing the game when Video Synchonize is choosen in OpenGL 3.2 driver. Direct3D 9.0 driver are running normal.

**To Reproduce**
1. Use OpenGL 3.2 video driver
2. Checkmark the Video -> Synchronize option
2a: GPU sync aren't making any difference.
4. Audio -> Synchronize must be off.
5. Run a game.

**Expected behavior**
The game should be running at normal speed. But is running with unlimited speed.

**Screenshots**
![image](https://user-images.githubusercontent.com/12163923/221378541-360e32ca-8a04-4a79-8377-7e8b38dbc7c7.png)

**Additional context**

**Comment by LukeUsher** [comment]
I have never been able to reproduce this locally; gpu sync works perfectly with OpenGL on my machine...

I think it's important to get more info; for example: what GPU vendor/driver you have, since it's more than likely a driver issue than an ares issue (but perhaps we can work around it, but we can't do so without a test case)

Also check your monitor refresh rate; if you're using a 144hz monitor for example, naturally gpu sync (vblank) won't be limited to 60hz.

**Comment by Shideravan** [comment]
I cannot reproduce anymore this issue in the most recent version of ares. Probably this was fixed in any point and/or I changed drivers of settings in the reference system used for testing.
If the issue return later in any form (or somebody else experience the same problem), we can reopen this issue.
